fix: automatic contrasting colors for texts when using color override
ivan-lednev/obsidian-day-planner pull request #506
Opened 2024-08-01 01:12 UTC by wcruz-br

Add automatic contrasting colors to texts on overrided background colors.

After @ivan-lednev asked to use `getTextColorWithEnoughContrast` over @bogdansalyp 's proposal #480 , I tried to implement it. First time with Svelte, but I think I did it right.

May resolve #481

2024-09-17 16:20 UTC, wcruz-br commented
Any chance of merging this? It would be great. Tell me if I can help anyway else.

2024-09-18 17:43 UTC, ivan-lednev requested changes

2024-09-18 17:43 UTC, ivan-lednev commented on src/ui/components/local-time-block.svelte
> +  );
This solution is simple, and it works, but let's keep all the color related code in one place. This should go into `src/ui/hooks/use-color.ts`. There, the same calculation is made for a different feature: colored timelines. We should check if a task matches an override there, and return the override colors. Overrides should take precedence over colored timeline colors.

2024-11-01 20:59 UTC, ivan-lednev commented
Closing this as stale. I've already fixed this myself.

2024-11-01 20:59 UTC, closed without merging