feat: display different stripes for tentative and declined events Google Calendar
ivan-lednev/obsidian-day-planner pull request #540
Opened 2024-09-08 09:35 UTC by ramandv

This will be helpful in planning the day easily. 
Sometimes user would have mentioned Rsvp No or Maybe. He/she does not need to bother about those events in planning their day. 
Basically Rsvp status visibility will be helpful in planning the day

**MAYBE rsvp status = striped box**
![](https://github.com/user-attachments/assets/fbc7bb75-d762-4e37-b5e0-07276c2017a2)

**Declined rsvp status = cross striped box**
![image](https://github.com/user-attachments/assets/f69c4202-2469-4db0-9f51-b6b412355bee)

Currently, it has been implemented for Google calendar. There needs to be minor tweaks for other calendars.
If this feature is useful for others, i can implement for other calendars too.

2024-09-08 09:36 UTC, ramandv commented
@ivan-lednev 
Just updated the code to the latest master. Let me know your thought even if you feel this feature is not useful.

2024-09-12 11:10 UTC, ivan-lednev commented
Hello, @ramandv, this is definitely useful! I'll review your changes once I have some capacity.

2024-09-18 18:29 UTC, ivan-lednev requested changes

2024-09-18 18:29 UTC, ivan-lednev commented on src/types.ts
> +  // Add the RSVP status property
Here and everywhere, please remove all the comments. They don't help me understand the code, and they add visual clutter.

2024-09-18 18:29 UTC, ivan-lednev commented on src/types.ts
> +  rsvpStatus?: string;
1. This should go to the new `RemoteTask` type (it's on the latest version of main.
2. It should be a type union of string values, not a string.

2024-09-18 18:29 UTC, ivan-lednev commented on src/ui/components/remote-time-block.svelte
> +    position: relative;
Why do you need to change positioning or default color?

2024-09-18 18:29 UTC, ivan-lednev commented on src/ui/components/remote-time-block.svelte
> +    padding-left: var(--size-4-2);
I think it's better to style the ribbon, not the whole block. This is what people using Teams and Outlook are used to, it also looks much cleaner.
1. Use an empty ribbon with a colorful border for declined events
2. Use a ribbon with colored stripes for tentative events

Example from teams:
![image](https://github.com/user-attachments/assets/115afaf8-a6e7-4ece-a091-59caa777ba86)

2024-09-18 18:29 UTC, ivan-lednev commented on src/util/ical.ts
> +function getRsvpStatus(icalEvent: WithIcalConfig<ical.VEvent>): string {
Ical events have a `status` field (at least the ones from Outlook that I've just checked):
![image](https://github.com/user-attachments/assets/b86f9ecf-cda2-43b1-b37d-93e255b5abb6)
Have you checked them on Google events?

If this is so, you can get rid of all this parsing all together and just use status straight from the event.

2024-09-18 18:29 UTC, ivan-lednev commented on src/util/ical.ts
> +    rsvpStatus: rsvpStatus,
Can be shortened to `rsvpStatus`.

2024-09-20 10:15 UTC, closed without merging